config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :availabilities

  resources :barbers do
    resources :availabilities
    resources :reviews
    resources :appointments
    resources :barbershops
    resources :barber_services
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="container-footer">
 <hr>
 <button type="button" class="btn btn-text btn-lg" data-toggle="modal" data-target="#myModal">
  Terms
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Terms and Conditions</h4>
      </div>
      <div class="modal-body">
        <div class="title">
          Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the www.barbapp.com website (the "Service") operated by Barber ("us", "we", or "our").
          <br /><br />
          Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Service.
          By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service. This Terms and Conditions was created with the Terms and Conditions Generator from TermsFeed.
          Accounts
          When you create an account with us, you must provide us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.
          You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password, whether your password is with our Service or a third-party service.
          You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.
          Links To Other Web Sites
          Our Service may contain links to third-party web sites or services that are not owned or controlled by Barber.
          Barber has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that Barber shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.
          We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.
          Termination
          We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
          All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.
          We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
          Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service.
          All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.
          Governing Law
          These Terms shall be governed and construed in accordance with the laws of Netherlands, without regard to its conflict of law provisions.
          Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.
          Changes.
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
          By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.
          Contact Us
          If you have any questions about these Terms, please contact us.

        </div>

        <div class="example">

          <div class="modal">
            <button class="close toggleModal">Close</button>
          </div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="join-app-btn">
  <%= link_to ' Join the BarberApp', new_barber_path, class: "btn btn-default" %>
</div>
<div class="text-center">
  <a href="https://www.facebook.com"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
  <a href="https://twitter.com"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
  <a href="https://plus.google.com/"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
  <a href="mailto:barber@pp.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
</div>
<hr>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "beardman.png" %>
  <% end %>

  <ul class="nav nav-pills">
    <li role="presentation"><%= link_to 'Barbers', barbers_path %>
    </li>
    <li>
    <% if current_user %>
      <% if current_user.barber %>
      <%= link_to 'My Profile', barber_path(current_user.barber)  %>
      <% end %>
      <% end %>
    </li>
    <li>

		<% if current_user %>
      <% if current_user.barber %>
        <% if current_user.barber.appointments.none? %>
          <%= link_to 'No Appointments Yet!', barbers_path %>
        <% else %>
          <%= link_to 'Agenda', barber_appointments_path(current_user.barber) %>
        <% end %>
    	<% elsif current_user %>
       	<% if current_user.appointments.none? %>
        	<%= link_to 'Book an Appointment!', barbers_path %>
        <% else %>
          <%= link_to 'View Appointment', barber_appointment_path(current_user.appointments.first.barber,
          current_user.appointments.first) %>
        <% end %>
       <% end %>
     <% end %>
    </li>
  </ul>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- tabs -->



    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

    <!-- Notification -->


    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%#= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% else %>

    <!-- Login text link -->

    <% end %>

    <!-- Button (call-to-action) -->
    <% if current_user %>
      <div id="logout">
      <%= link_to destroy_user_session_path, method: :delete do %>
      <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
      <% end %>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>