config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :availabilities

  resources :barbers do
    resources :availabilities
    resources :reviews
    resources :appointments
    resources :barbershops
    resources :barber_services
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/barber.rb
class Barber < ApplicationRecord
  geocoded_by :location

  after_validation :geocode, if: :location_changed?
  include PgSearch

  multisearchable against: [:name], using: {tsearch: {any_word: true}}
    # using: { tsearch: { dictionary: 'english' } }

  belongs_to :user
  belongs_to :barbershop, optional: true
  has_many :appointments, through: :barber_services, dependent: :destroy
  has_many :barber_services, dependent: :destroy
  has_many :services, through: :barber_services
  has_many :reviews, dependent: :destroy
  has_many :availabilities, dependent: :destroy
  mount_uploader :photo, PhotoUploader

  validates :name, :description, :location, presence: true

  def walk_distance(lat, lng)
    barber_lng = self.longitude
    barber_lat = self.latitude
    url = "https://maps.googleapis.com/maps/api/directions/json?origin=#{lat},#{lng}&destination=#{barber_lat},#{barber_lng}&sensor=false&mode=walking&key=#{ENV["GOOGLE_WEBS_API"]}"
    buffer = open(url).read
    result = JSON.parse(buffer)
    result["routes"][0]["legs"][0]["distance"]["text"]
  end

  def car_distance(lat, lng)
    barber_lng = self.longitude
    barber_lat = self.latitude
    url = "https://maps.googleapis.com/maps/api/directions/json?origin=#{lat},#{lng}&destination=#{barber_lat},#{barber_lng}&sensor=false&mode=driving&key=#{ENV["GOOGLE_WEBS_API"]}"
    buffer = open(url).read
    result = JSON.parse(buffer)
    result["routes"][0]["legs"][0]["distance"]["text"]
  end

  def walk_duration(lat, lng)
    barber_lng = self.longitude
    barber_lat = self.latitude
    url = "https://maps.googleapis.com/maps/api/directions/json?origin=#{lat},#{lng}&destination=#{barber_lat},#{barber_lng}&sensor=false&mode=walking&key=#{ENV["GOOGLE_WEBS_API"]}"
    buffer = open(url).read
    result = JSON.parse(buffer)
    result["routes"][0]["legs"][0]["duration"]["text"]
  end

  def car_duration(lat, lng)
    barber_lng = self.longitude
    barber_lat = self.latitude
    url = "https://maps.googleapis.com/maps/api/directions/json?origin=#{lat},#{lng}&destination=#{barber_lat},#{barber_lng}&sensor=false&mode=driving&key=#{ENV["GOOGLE_WEBS_API"]}"
    buffer = open(url).read
    result = JSON.parse(buffer)
    result["routes"][0]["legs"][0]["duration"]["text"]
  end

  def available_times
    array = []
    self.availabilities.each do |slot|
      if slot.appointment == nil
        array << slot
      end
    end
      return array
  end
end

app/controllers/barbers_controller.rb
class BarbersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :find_barber, only: [:show, :edit, :update, :destroy]
  before_action :find_user, only: [:create]


  def index
    if params[:location].present?
      @barbers = Barber.near(params[:location], 10).order('distance')
    elsif params[:search].present?
      @pg_search_documents = PgSearch.multisearch(params[:search])
      @barbers = @pg_search_documents.map(&:searchable)
    else
     @barbers = Barber.where.not(latitude: nil, longitude: nil)
   end
 end



 def show
  @barbershop = @barber.barbershop
  @coordinates = Gmaps4rails.build_markers(@barber) do |barber, marker|
   marker.lat barber.latitude
   marker.lng barber.longitude
   marker.infowindow render_to_string(partial: "/barbers/map_box", locals: { barber: barber })
 end
end

def new
  if current_user.barber
    flash[:notice] = 'You are already have a profile bro!'
    redirect_to barber_path(current_user.barber)
  else
    @barber = Barber.new
    @services = Service.all
  end
end

def create
  @barber = Barber.new(barber_params)
  @barber.user = @user
  @barber.save!
  redirect_to barber_path(@barber)
end


def edit
  @barberservice = BarberService.new
  @services = Service.all
end

def update
  @barber.update(barber_params)
  redirect_to barber_path(@barber)
end

def destroy
  @barber.destroy
  redirect_to barbers_path
end

private

def find_user
  @user = current_user
end

def find_barber
  @barber = Barber.find(params[:id])
end

def barber_params
  params.require(:barber).permit(:name, :description, :location, :services, :photo, :photo_cache)
end
end

app/helpers/barbers_helper.rb
module BarbersHelper
end

app/views/barbers/_form.html.erb
<%= simple_form_for(@barber) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

app/views/barbers/_map_box.html.erb
<div class="map_box">
  <h1><%= barber.name %></h1>
 <p> <%= barber.location %> </p>
 <p> <%= link_to "Details", barber_path(barber), target: :blank, class: "btn btn-default" %> </p>
</div>

app/views/barbers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">

      <h1> Edit your page: <%= @barber.name %> </h1>


      <%= form_for(@barber) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control input-lg edit-input input-name" %>
      <br />
      <br />
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control input-lg edit-input" %>
      <br />
      <br />
      <%= f.label :location %>
      <%= f.text_area :location, class: "form-control input-lg edit-input" %>
      <%= f.submit %>
      <% end %>
    </div>

    <div class="col-md-4">
      <h2> Add New Services </h2>

      <%= simple_form_for([@barber, @barberservice]) do |f| %>
      <%= f.association :service %>
      <%= f.input :price %>
      <%= f.input :duration %>


      <%= f.submit %>
      <% end %>

      <h2> Current Services</h2>

      <% @barber.barber_services.each do |barber_service|  %>
      <li>
        <%= barber_service.name %>
        Set Price : <%= barber_service.price %>
        Time Need : <%= barber_service.duration %>
        <%= link_to 'Delete', barber_barber_service_path(@barber, barber_service), method: :delete, data: { confirm: "Are you sure? 1" } %>
      </li>
      <% end %>
    </div>
  </div>
</div>

app/views/barbers/index.html.erb
<div class="container">
	<div class="row">
    <div class="col-md-9-offset col-md-4-offset">
      <section class="first">
          <h3 class="effect">Find your barber</h3>
      </section>
      </div>
    </div>
  </div>

<div class="container container-index">
  <div class="row row-index">
    <% @barbers.each do |barber| %>
    <div class="col-xs-12  col-md-4">
    <%= link_to(barber) do %>
      <div class="card-background">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path(barber.picture ? barber.picture : "http://www.belmontbarbershop.com/wp-content/uploads/2013/05/intro_image.jpg" ) %>);">
          <%= image_tag "beardman.png", class: "card-user avatar" %>
        </div>
        <div class="card-location">
          <p> <%= barber.location %> </p>
        </div>
        <div class="card-hover">
          <p>
            <%= barber.description[0..100] %>...
            <% average = 0 %>
            <% barber.reviews.each do |e| %>
            <% average += e.rating.to_i %>
            <% end %>
          </p>
        </div>
        <h4>
          <%= link_to "#{barber.name}", barber_path(barber), class: "barber-name" %>
        </h4>
        <div class="card-rating">
          Rating:
          <% if barber.reviews.length == 0 %>
          <%= "Not Rated Yet!" %>
          <% else %>
          <%= average/barber.reviews.length %>
          <% end %>
        </div>
      </div>
      <% end  %>
    </div>
    <% end %>
  </div>
</div>

app/views/barbers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">

    <h1> We are going to need some information! </h1>


      <%= form_for(@barber) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control input-lg edit-input input-name" %>
      <br />
      <br />
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control input-lg edit-input" %>
      <br />
      <br />
      <%= f.label :location %>
      <%= f.text_area :location, class: "form-control input-lg edit-input" %>
      <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/barbers/show.html.erb
  <div class="profile-banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.35) 0%, rgba(0,0,0,0.35) 50%), url( <%= image_path("#{@barber.photo}") %>);">
    <div class="profile-banner-content">
      <section class="first">
        <h1 <span class="text-white"><%= @barber.name %></span></h1>
      </section>
    </div>
  </div>

  <!-- Barber_banner_2.png -->

  <div class="button-flex">
    <div class="file-upload">
      <% if @barber.user == current_user %>
      <%= simple_form_for(@barber) do |f| %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit "Update Profile picture", class: "btn-update" %>
      <% end %>
      <% end %>
    </div>

    <div class="btn-group">
      <% if @barber.user == current_user %>
      <%= link_to "Edit Profile", edit_barber_path(@barber), class: "edit-btn" %>
      <br>
      <%= link_to "Delete Profile", barber_path(@barber), class: "edit-btn", method: :delete, data: { confirm: "you sure?" } %>
      <% end %>
    </div>
  </div>


<div class="services-row">
  <div class="infobox">
    <h2>Services</h2>
    <% @barber.barber_services.each do |barber_service|  %>
    <p><i class="fa fa-scissors" aria-hidden="true"></i> <%= barber_service.name %> Price - <%= barber_service.price %> (+- <%= barber_service.duration %> minutes)</p>
    <% end %>
      <br>
    <% if current_user.barber == @barber  %>
      <%= link_to 'Agenda', barber_appointments_path(@barber), class: "edit-btn" %>
    <% else %>
  </div>

  <div class="book-box">
      <%= link_to "Book Appointment", new_barber_appointment_path(@barber), class:"edit-btn" %>
    <% end %>
  </div>

  <div class="description">
    <h2> <%= @barber.description %> </h2>
  </div>
</div>


  <div id="map" style="width: 100%; height: 350px; border-style: groove;"></div>

  <div class="review-box">
    <h2>Reviews</h2>
    <% @barber.reviews.each do |review| %>

    <h4>  <%= review.description %></h4>
    <p> posted by : <%= review.user.email %> at <%= review.user.created_at.strftime("%b %e, %l:%M %p") %></p>

    <p><% review.rating.to_i.times do %> <i class='fa fa-star' aria-hidden='true'></i> <% end %> </p>
    <% if review.user == current_user %>
    <%= link_to 'Edit Review', edit_barber_review_path(@barber, review) %>
    <br>
    <%= link_to "Delete", barber_review_path(@barber, review), method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
    <% end %>
    <% if current_user.barber != @barber %>
    <%= link_to 'Leave a review!', new_barber_review_path(@barber), class: "btn btn-default" %>
    <% end %>
  </div>


  <div class="review-photos">
    <div class=container>
      <div class=row>
        <h3> Some of the user pictures</h3>
        <% @barber.reviews.each do |review| %>
        <div class="col-sm-3 ">
          <div class= image-attr>
            <a href="<%= review.photo %>" class="swipebox">
              <%= image_tag review.photo, class: "img-responsive" %>
            </a>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>





  <% content_for(:after_js) do %>
  <%= javascript_tag do %>
  var styles = [{"featureType":"landscape","stylers":[{"hue":"#FFBB00"},{"saturation":43.400000000000006},{"lightness":37.599999999999994},{"gamma":1}]},{"featureType":"road.highway","stylers":[{"hue":"#FFC200"},{"saturation":-61.8},{"lightness":45.599999999999994},{"gamma":1}]},{"featureType":"road.arterial","stylers":[{"hue":"#FF0300"},{"saturation":-100},{"lightness":51.19999999999999},{"gamma":1}]},{"featureType":"road.local","stylers":[{"hue":"#FF0300"},{"saturation":-100},{"lightness":52},{"gamma":1}]},{"featureType":"water","stylers":[{"hue":"#0078FF"},{"saturation":-13.200000000000003},{"lightness":2.4000000000000057},{"gamma":1}]},{"featureType":"poi","stylers":[{"hue":"#00FF6A"},{"saturation":-1.0989010989011234},{"lightness":11.200000000000017},{"gamma":1}]}]

  $(document).ready(function() {
  var handler = Gmaps.build('Google');
  handler.buildMap({ provider: {scrollwheel: false, styles: styles}, internal: { id: 'map' } }, function() {
  markers = handler.addMarkers(<%= raw @coordinates.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  if (markers.length == 0) {
  handler.getMap().setZoom(2);
} else if (markers.length == 1) {
handler.getMap().setZoom(14);
handler.disableScrollWheelZoom();

}
});
});
<% end %>
<% end %>