config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :availabilities

  resources :barbers do
    resources :availabilities
    resources :reviews
    resources :appointments
    resources :barbershops
    resources :barber_services
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :barber_service
  belongs_to :availability
  belongs_to :user
  has_one :barber, through: :barber_service
end

app/controllers/appointments_controller.rb
  class AppointmentsController < ApplicationController
  before_action :find_appointment, only: [:show, :edit, :update, :destroy]
  before_action :find_user, only: [:show, :new, :destroy, :edit, :create, :update, :index]
  before_action :find_barber_service, only: [:create]
  before_action :find_barber, only: [:show, :index, :new, :destroy, :edit, :create, :update]
  before_action :find_availability, only: [:create]

  respond_to :html, :js

  def index
    @availability = Availability.new
    @availabilities = Availability.where(barber: @barber)

    @appointments = @barber.appointments
    #@appointments_by_date = @appointments.group_by(&:date).map { |k, v| [k.to_date, v] }.to_h
    @user = current_user
    #@date = params[:date] ? Date.parse(params[:date]) : Date.today
    @date = params[:month] ? Date.parse(params[:month]) : Date.today

    respond_to do |format|
      format.html
    end
  end

  def show
  end

  def new
    @barber_services = @barber.barber_services
    @availabilities = Availability.where(barber: @barber)
    @appointments = @barber.appointments
    #@appointments_by_date = @appointments.group_by(&:date).map { |k, v| [k.to_date, v] }.to_h
    @appointment = Appointment.new
    #@date = params[:date] ? Date.parse(params[:date]) : Date.today
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def create
    @appointment = Appointment.new(params_appointment)
    @appointment.barber_service_id = @barber_service.id
    @appointment.availability_id = @availability.id
    @appointment.user = current_user
    @availability.appointment = @appointment.id
    @availability.save!
    @appointment.save!
    if @appointment.save != true
      flash[:notice] = "Please fill out the form properly"
      redirect_to new_barber_appointment_path(@barber)
    else
      if current_user.barber
        redirect_to barber_appointment_path(@barber, @appointment)
      else
        redirect_to barber_appointment_path(@barber, @appointment)
      end
    end
  end

  # def edit
  #       @barber_services = @barber.barber_services

  # end

  # def update
  #   @appointment.barber_service = @barber_service
  #   raise
  #   @appointment.update(params_appointment)
  #   if current_user.barber
  #     redirect_to barber_appointments_path(@barber, @appointment)
  #   else
  #     redirect_to barber_appointment_path(@barber, @appointment)
  #   end
  # end

  def destroy
    @appointment.destroy
    if current_user.barber == @barber
      redirect_to barber_appointments_path(@barber)
     else
      redirect_to root_path
    end
  end

  private

  def find_barber
    @barber = Barber.find(params[:barber_id])
  end

  def find_appointment
    @appointment = Appointment.find(params[:id])
  end

  def find_barber_service
    @barber_service = BarberService.find(params["appointment"][:barber_service])
  end

  def find_user
    @user = current_user
  end

  def find_availability
    @availability = Availability.find(params["appointment"][:availability_id])
  end

  def params_appointment
    params.require(:appointment).permit(:availability_id, :barber_service_id, :id).merge(user_id: current_user.id)
  end
end

app/views/appointments/_form.html.erb
<%# if @barber.availabilities.any? %>


<%= simple_form_for([@barber, @appointment]) do |f| %>

  <%= f.input :availability_id, collection: @barber.available_times, label_method: :start, value_method: :id %>

  <%= f.input :barber_service, collection: @barber_services  %>
<!-- <p> -->
  <%= f.button :submit %>
<!-- </p> -->
<% end %>


<%# else %>
<!-- <p>
  This barber does not have any availability...
</p> -->
<%# end %>

app/views/appointments/create.js.erb
$('#appointments').html("<%= j (render @appointment) %>");
$('#appointment-form').slideUp(350);

app/views/appointments/edit.html.erb
<h1>Edit appointment </h1>

<h4>
  Availability
</h4>

      <%= simple_form_for ([@barber, @appointment]) do |f| %>

      <%= f.input :date, as: :datetime, html5: true %>
      <%= f.input :barber_service, collection: @barber_services  %>
      <p>
        <%= f.button :submit %>
      </p>
      <% end %>

app/views/appointments/index.html.erb
<div class="container">
  <div class="appointment-body">
    <h2>
      Hi, <%= @barber.name %>
    </div>


    <h4> Add Availablitiy</h4>
    <%= simple_form_for ([@barber, @availability]) do |f| %>
    <%= f.input :start, as: :datetime, html5: true %>
    <%= f.input :end, as: :datetime, html5: true %>
    <%= f.submit %>
    <% end %>

  </div>
  <div class="appointment-body">
    <h2>
      These are your booked appointments!
    </h2>
    <div class="row">

      <% @barber.appointments.each do |appointment| %>
      <p>Appointment with <%= appointment.user.name %> on the
        <%= appointment.availability.start.strftime("%b %e, %l:%M %p") %> untill <%= appointment.availability.end.strftime("%b %e, %l:%M %p") %> for a <%= appointment.barber_service.name %>
        <% end %>
      </p>
    </div>
  </div>


<div id="appointments">
    <h3 id="month">
    <%= link_to "<", date: @date.prev_week %>
    <%= @date.strftime("%B %Y") %>
    <%= link_to ">", date: @date.next_week %>
    </h3>
    <%= calendar @date do |calendar_date| %>
      <%= calendar_date.day %>
      <% @availabilities.each do |availability| %>
        <% cover = availability.start.to_date.between?(calendar_date, calendar_date.end_of_day) %>
        <% if cover %>
          <% if availability.appointment  %>
              <div class="appointment-booked">
              <%= availability.start.strftime("%l:%M %p") %>
                -
              <%= availability.end.strftime("%l:%M %p") %>
              </div>
            <% else %>
              <div class="appointment-availability">
                <%= availability.start.strftime("%l:%M %p") %>
                  -
                <%= availability.end.strftime("%l:%M %p") %>
              </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
 </div>
</div>

app/views/appointments/new.html.erb
<div class="container">
  <div class="row"">
    <h2> Spots still open</h2>
    <% @barber.availabilities.each do |availability| %>
      <% if availability.appointment.nil? %>
        <p>
          <%= "#{availability.start.strftime("%b %e, %l:%M %p")} to #{availability.end.strftime("%b %e, %l:%M %p")}" %>
          <br>
        </p>
      <% end %>
    <% end %>
  </div>


  <div id="appointments">
    <h3 id="month">
    <%= link_to "<", date: @date.prev_week %>
    <%= @date.strftime("%B %Y") %>
    <%= link_to ">", date: @date.next_week %>
    </h3>
    <%= calendar @date do |calendar_date| %>
      <%= calendar_date.day %>
      <% @availabilities.each do |availability| %>
        <% cover = availability.start.to_date.between?(calendar_date, calendar_date.end_of_day) %>
        <% if cover %>
          <% if availability.appointment  %>
            <div class="appointment-booked">
              <p>Booked</p>
            </div>
          <% else %>
          <div class="appointment-background">
            <div class="appointment-availability">
              <%= availability.start.strftime("%l:%M %p") %>
              -
              <%= availability.end.strftime("%l:%M %p") %>
              <br>

            </div>
            <div class="appointment-hover">
                <button type="button" id="book-btn" class="btn btn-default btn-block appointment-book" data-toggle="modal" data-target="  #book-modal" data-start-time="<%= availability.start %>">
                  Book
                </button>
            </div>
          </div>
          <% end %>
        <% end %>
      <% end %>
   <% end %>
 </div>



<!-- Modal with form -->
  <div class="modal fade bd-example-modal-sm" id="book-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
        <div class="book-modal">
          <%= simple_form_for([@barber, @appointment]) do |f| %>

          <%= f.input :availability_id, collection: @barber.available_times, label_method: :start, value_method: :id %>

          <%= f.input :barber_service, collection: @barber_services  %>
          <p>
          <%= f.button :submit %>
          </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/appointments/show.html.erb
<div class="appointment-body">
  <div class="child">
    <h2>
      <strong>
        Your Appointment with <%= @barber.name %>
      </strong>
    </h2>
  </div>
  <!-- user -->

  <div class="child">
    <ul>
      <li>
        The date of your appointment: <%= @appointment.availability.start.strftime("%b %e, %l:%M %p")  %> untill <%= @appointment.availability.end.strftime("%b %e, %l:%M %p")  %>
      </li>
      <li>
        The location of your appointment: <%= @barber.location %>
      </li>
      <li>
        For a <%= @appointment.barber_service.name  %>
      </li>
    </ul>
    <br>
  </div>

<!--   <div class="child-btns">
    <div id="update">
      <ul>
        <li>
          <%#= link_to 'Update Appointment', edit_barber_appointment_path(@barber, @appointment), class: "btn btn-primary" %>
        </li>
      </ul>
    </div> -->

    <div id="cancel">
      <ul>
        <li>
          <%= link_to 'Cancel Appointment', barber_appointment_path(@barber, @appointment), class: "btn btn-primary", method: :delete, data: { confirm: "Are you sure?" } %>
        </li>
      </ul>
    </div>
  </div>
</div>